/**
 * AdvanceHub ABI. Generated by `packages/core/scripts/gen-loan-abis.ts` from the compiled
 * Foundry artifact (`contracts/out/AdvanceHub.sol/AdvanceHub.json`) - never hand-copied.
 * Regenerate after any change to `contracts/src/AdvanceHub.sol`:
 *   cd contracts && forge build
 *   cd ../packages/core && node scripts/gen-loan-abis.ts
 */
export const advanceHubAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "cfg",
        "type": "tuple",
        "internalType": "struct AdvanceHub.Config",
        "components": [
          {
            "name": "usdc",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "weth",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ccaFactory",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ethUsdFeed",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sequencerFeed",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reputationRegistry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "maxStaleness",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "slippageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minActivityUsdc",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "underwriter_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "owner_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "escrowDeployer_",
        "type": "address",
        "internalType": "contract EscrowDeployer"
      },
      {
        "name": "loanDeployer_",
        "type": "address",
        "internalType": "contract LoanDeployer"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CARD_HOOK_GAS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REPUTATION_HOOK_GAS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TICK_SPACING_Q96",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "abort",
    "inputs": [
      {
        "name": "ts",
        "type": "tuple",
        "internalType": "struct TermSheet",
        "components": [
          {
            "name": "agentTreasury",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentCard",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "feesManager",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expectedShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noteSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "floorCents",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minPrincipal",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "auctionBlocks",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "drawLimit",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "drawPeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gracePeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memoHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "aborted",
    "inputs": [
      {
        "name": "termSheetHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "config",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AdvanceHub.Config",
        "components": [
          {
            "name": "usdc",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "weth",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ccaFactory",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "router",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "ethUsdFeed",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "sequencerFeed",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reputationRegistry",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "maxStaleness",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "slippageBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minActivityUsdc",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployEscrow",
    "inputs": [
      {
        "name": "ts",
        "type": "tuple",
        "internalType": "struct TermSheet",
        "components": [
          {
            "name": "agentTreasury",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentCard",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "feesManager",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expectedShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noteSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "floorCents",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minPrincipal",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "auctionBlocks",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "drawLimit",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "drawPeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gracePeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memoHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "eip712Domain",
    "inputs": [],
    "outputs": [
      {
        "name": "fields",
        "type": "bytes1",
        "internalType": "bytes1"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "version",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "chainId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "extensions",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "escrowDeployer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract EscrowDeployer"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "liveLoanOf",
    "inputs": [
      {
        "name": "card",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "loan",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct AdvanceHub.Loan",
        "components": [
          {
            "name": "ts",
            "type": "tuple",
            "internalType": "struct TermSheet",
            "components": [
              {
                "name": "agentTreasury",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "agentCard",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "agentId",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "feesManager",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "poolId",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "expectedShares",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "noteSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "floorCents",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "minPrincipal",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "auctionBlocks",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "drawLimit",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "drawPeriod",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "gracePeriod",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "deadline",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "nonce",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "memoHash",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "escrow",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "note",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "creditLine",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "auction",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum IAdvance.LoanStatus"
          },
          {
            "name": "openedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "activatedAt",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "loanCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "loanDeployer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract LoanDeployer"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "loanIdOf",
    "inputs": [
      {
        "name": "termSheetHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "markDefault",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "nonceUsed",
    "inputs": [
      {
        "name": "signer",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "nonce",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "onAuctionSettled",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "graduated",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "onRepaid",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "openLoan",
    "inputs": [
      {
        "name": "ts",
        "type": "tuple",
        "internalType": "struct TermSheet",
        "components": [
          {
            "name": "agentTreasury",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentCard",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "feesManager",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expectedShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noteSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "floorCents",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minPrincipal",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "auctionBlocks",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "drawLimit",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "drawPeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gracePeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memoHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      },
      {
        "name": "signature",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictEscrow",
    "inputs": [
      {
        "name": "ts",
        "type": "tuple",
        "internalType": "struct TermSheet",
        "components": [
          {
            "name": "agentTreasury",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentCard",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "feesManager",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expectedShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noteSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "floorCents",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minPrincipal",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "auctionBlocks",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "drawLimit",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "drawPeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gracePeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memoHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setUnderwriter",
    "inputs": [
      {
        "name": "newUnderwriter",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "termSheetDigest",
    "inputs": [
      {
        "name": "ts",
        "type": "tuple",
        "internalType": "struct TermSheet",
        "components": [
          {
            "name": "agentTreasury",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentCard",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "agentId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "feesManager",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "expectedShares",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noteSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "floorCents",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minPrincipal",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "auctionBlocks",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "drawLimit",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "drawPeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "gracePeriod",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "deadline",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "nonce",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memoHash",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "termSheetStatus",
    "inputs": [
      {
        "name": "termSheetHash",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum IAdvance.LoanStatus"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "underwriter",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "CardHookSkipped",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "selector",
        "type": "bytes4",
        "indexed": false,
        "internalType": "bytes4"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "CloseAttemptFailed",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "target",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "reason",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EIP712DomainChanged",
    "inputs": [],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LoanAborted",
    "inputs": [
      {
        "name": "termSheetHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LoanActivated",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "principal",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LoanDefaulted",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "lastRevenueAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LoanFailed",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LoanOpened",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "termSheetHash",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "agentTreasury",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "escrow",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "note",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "creditLine",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "auction",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LoanRepaid",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "totalRepaid",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "currentOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newPendingOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReputationPosted",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "value",
        "type": "int128",
        "indexed": false,
        "internalType": "int128"
      },
      {
        "name": "tag",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReputationSkipped",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "reason",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "UnderwriterUpdated",
    "inputs": [
      {
        "name": "previousUnderwriter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newUnderwriter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyAborted",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyOpened",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadSignature",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadTerms",
    "inputs": [
      {
        "name": "code",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "CardInUse",
    "inputs": [
      {
        "name": "loanId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "EscrowNotBeneficiary",
    "inputs": [
      {
        "name": "shares",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "expected",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "Expired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidCard",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidShortString",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NonceUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotBorrower",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotDelinquent",
    "inputs": [
      {
        "name": "eligibleAt",
        "type": "uint64",
        "internalType": "uint64"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotLoanContract",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotPendingOwner",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotWethPool",
    "inputs": []
  },
  {
    "type": "error",
    "name": "StringTooLong",
    "inputs": [
      {
        "name": "str",
        "type": "string",
        "internalType": "string"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnsupportedPool",
    "inputs": [
      {
        "name": "agentToken",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "WrongStatus",
    "inputs": [
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum IAdvance.LoanStatus"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
