/**
 * Regenerates `src/abis/{advanceHub,creditLine,revenueEscrow,revenueNote}.ts` from the compiled
 * Foundry artifacts at `contracts/out/<Contract>.sol/<Contract>.json`. Run `forge build` in
 * `contracts/` first.
 *
 * These ABIs are never hand-copied: this script is the only thing that writes them, so they stay
 * byte-for-byte in sync with the deployed contracts (same convention as
 * `gen-agent-card-abi.ts`/`agentCard.ts`).
 *
 * Usage (from packages/core): node scripts/gen-loan-abis.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

interface ForgeArtifact {
  abi: unknown[];
}

interface Target {
  contract: string;
  exportName: string;
  outFile: string;
}

const targets: Target[] = [
  { contract: "AdvanceHub", exportName: "advanceHubAbi", outFile: "advanceHub.ts" },
  { contract: "CreditLine", exportName: "creditLineAbi", outFile: "creditLine.ts" },
  { contract: "RevenueEscrow", exportName: "revenueEscrowAbi", outFile: "revenueEscrow.ts" },
  { contract: "RevenueNote", exportName: "revenueNoteAbi", outFile: "revenueNote.ts" },
];

for (const { contract, exportName, outFile } of targets) {
  const artifactPath = resolve(here, `../../../contracts/out/${contract}.sol/${contract}.json`);
  const outPath = resolve(here, `../src/abis/${outFile}`);

  let artifact: ForgeArtifact;
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as ForgeArtifact;
  } catch (err) {
    throw new Error(
      `gen-loan-abis: could not read ${artifactPath} - run "forge build" in contracts/ first (${String(err)})`,
    );
  }

  const contents = `/**
 * ${contract} ABI. Generated by \`packages/core/scripts/gen-loan-abis.ts\` from the compiled
 * Foundry artifact (\`contracts/out/${contract}.sol/${contract}.json\`) - never hand-copied.
 * Regenerate after any change to \`contracts/src/${contract}.sol\`:
 *   cd contracts && forge build
 *   cd ../packages/core && node scripts/gen-loan-abis.ts
 */
export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  writeFileSync(outPath, contents);
  console.log(`wrote ${outPath}`);
}
