/**
 * Regenerates `src/abis/agentCard.ts` from the compiled Foundry artifact at
 * `contracts/out/AgentCard.sol/AgentCard.json`. Run `forge build` in `contracts/` first.
 *
 * The ABI is never hand-copied: this script is the only thing that writes
 * `agentCard.ts`, so it stays byte-for-byte in sync with the deployed contract.
 *
 * Usage (from packages/core): node scripts/gen-agent-card-abi.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifactPath = resolve(here, "../../../contracts/out/AgentCard.sol/AgentCard.json");
const outPath = resolve(here, "../src/abis/agentCard.ts");

interface ForgeArtifact {
  abi: unknown[];
}

let artifact: ForgeArtifact;
try {
  artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as ForgeArtifact;
} catch (err) {
  throw new Error(
    `gen-agent-card-abi: could not read ${artifactPath} - run "forge build" in contracts/ first (${String(err)})`,
  );
}

const contents = `/**
 * AgentCard ABI. Generated by \`packages/core/scripts/gen-agent-card-abi.ts\` from the
 * compiled Foundry artifact (\`contracts/out/AgentCard.sol/AgentCard.json\`) - never hand-copied.
 * Regenerate after any change to \`contracts/src/AgentCard.sol\`:
 *   cd contracts && forge build
 *   cd ../packages/core && node scripts/gen-agent-card-abi.ts
 */
export const agentCardAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

writeFileSync(outPath, contents);
console.log(`wrote ${outPath}`);
