/**
 * Regenerates `src/abis/*.generated.ts` from `contracts/out` (forge's build artifacts) —
 * the only supported way this SDK's ABIs for Advance's own contracts get updated. Never hand-
 * copy an ABI: run `forge build` in `contracts/` first, then `pnpm generate:abis` here.
 *
 * Usage (from `packages/sdk`): pnpm generate:abis
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsOut = resolve(here, "../../../contracts/out");
const abisDir = resolve(here, "../src/abis");

/** `sourceFile` is the `.sol` file name under `contracts/src` (or `contracts/src/<dir>`);
 * `contractName` is the artifact name forge nests it under. */
interface AbiTarget {
  sourceFile: string;
  contractName: string;
  /** Exported identifier, e.g. `advanceHubAbi`. */
  exportName: string;
  /** Output file basename under `src/abis/`. */
  outFile: string;
}

const targets: AbiTarget[] = [
  { sourceFile: "AdvanceHub.sol", contractName: "AdvanceHub", exportName: "advanceHubAbi", outFile: "advanceHub.generated.ts" },
  { sourceFile: "CreditLine.sol", contractName: "CreditLine", exportName: "creditLineAbi", outFile: "creditLine.generated.ts" },
  { sourceFile: "RevenueEscrow.sol", contractName: "RevenueEscrow", exportName: "revenueEscrowAbi", outFile: "revenueEscrow.generated.ts" },
  { sourceFile: "RevenueNote.sol", contractName: "RevenueNote", exportName: "revenueNoteAbi", outFile: "revenueNote.generated.ts" },
  { sourceFile: "AgentCard.sol", contractName: "AgentCard", exportName: "agentCardAbi", outFile: "agentCard.generated.ts" },
  { sourceFile: "ICCA.sol", contractName: "ICCA", exportName: "iccaAbi", outFile: "icca.generated.ts" },
  {
    sourceFile: "IDopplerFeesManager.sol",
    contractName: "IDopplerFeesManager",
    exportName: "dopplerFeesManagerAbi",
    outFile: "dopplerFeesManager.generated.ts",
  },
];

interface ForgeArtifact {
  abi: unknown[];
}

function loadAbi(target: AbiTarget): unknown[] {
  const path = resolve(contractsOut, `${target.sourceFile}/${target.contractName}.json`);
  const artifact = JSON.parse(readFileSync(path, "utf8")) as ForgeArtifact;
  return artifact.abi;
}

function renderModule(target: AbiTarget, abi: unknown[]): string {
  const header =
    `// Generated by packages/sdk/scripts/generate-abis.ts from contracts/out — do not edit by hand.\n` +
    `// Regenerate: (cd contracts && forge build) && (cd packages/sdk && pnpm generate:abis)\n\n`;
  const body = `export const ${target.exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  return header + body;
}

function main(): void {
  mkdirSync(abisDir, { recursive: true });
  const exportLines: string[] = [
    "// Generated by packages/sdk/scripts/generate-abis.ts — do not edit by hand.\n",
  ];

  for (const target of targets) {
    const abi = loadAbi(target);
    writeFileSync(resolve(abisDir, target.outFile), renderModule(target, abi));
    exportLines.push(`export { ${target.exportName} } from "./${target.outFile.replace(/\.ts$/, ".js")}";`);
    console.log(`wrote src/abis/${target.outFile} (${abi.length} abi entries)`);
  }

  writeFileSync(resolve(abisDir, "generated.ts"), exportLines.join("\n") + "\n");
  console.log("wrote src/abis/generated.ts");
}

main();
